### ISSUE TITLE
没有指定权限要求的应该放行

### ISSUE THREAD

**Issue by qjebbs** [tango-contrib/rbac#2]
假设我有配置是这样的：
```Go
type Action struct {
    Perm `POST:"write"`
}
```
与这个问题相关的代码是，
```Go
tag, ok, hasColon := lookup(permTag, ctx.Req().Method)
if hasColon {
    if !ok {
        opt.OnNoPerm(ctx)
        return
    }
} else {
    tag = permTag
}
```
我的初衷是GET不需要校验权限，那么这个配置下，代码中的`ok==false`，直接告诉我没权限了。
如果我换个写法：
```Go
type Action struct {
    Perm `GET:"" POST:"write"`
}
```
ok这一步是过去了，但得出的`tag=""`，尝试检查空字符串的权限，返回也是没权限。

建议：
```Go
tag, ok, hasColon := lookup(permTag, ctx.Req().Method)
if hasColon {
    if !ok || tag=="" {
        ctx.Next()
        return
    }
} else {
    tag = permTag
}
```

**Comment by qjebbs** [comment]
roles 那部分应该也是一样的逻辑吧。另外，role可以考虑支持这样的定义吗：
```
type Action struct {
    Role `GET:"reader, writer" POST:"writer"`
}
```

**Comment by lunny** [comment]
多权限和多角色后面确实有需要了再支持。

**Comment by hsluoyz** [comment]
@qjebbs , 现在tango增加了另一个权限插件：https://github.com/tango-contrib/authz ，这个插件是基于[Casbin](https://github.com/casbin/casbin-authz-plugin)的。

这个插件的策略格式可能更简单点：

可以采用*代表任意值，也可以采用正则表达式来匹配任意字段，策略的格式是：
```
p, 登录用户名（如果有的话）, URL, HTTP方法
```

比如实现任何人GET任意URL不需要校验权限：
```
p, *, *, GET
```

更复杂的一点的策略：
```
p, alice, /alice_data/*, GET
p, alice, /alice_data/resource1, POST
p, bob, /alice_data/resource2, GET
p, bob, /bob_data/*, POST
```

是指alice用户可以GET匹配/alice_data/*的任意URL，可以POST /alice_data/resource1，等等。

另外这个插件也支持RBAC角色，角色之间可以继承。策略可以存储在文件，也可以存储在数据库里。
